version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/agent"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/bootclasspath"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/classifier"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/copy"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/dependency-management"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.veithen.cosmos:cosmos-osgi-runtime"
      - dependency-name: "org.slf4j:slf4j-api"
  - package-ecosystem: "maven"
    directory: "/src/it/generate-test-resources"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/includes-excludes"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/intro-sample"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/pax-exam"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/pax-exam-single-module"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
